jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      node_11_x:
        node_version: 11.x
      node_10_x:
        node_version: 10.x
      node_8_x:
        node_version: 8.x
    maxParallel: 5
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
    displayName: Install Node.js
  - bash: npm i
    displayName: Install dependencies
  - bash: npm run ci-lint
    displayName: Check linting
  - bash: npm run ci-cov
    displayName: Run tests with code coverage
    condition: ne(variables['node_version'], '8.x')
  - bash: npm run ci-test
    displayName: Run tests without code coverage
    condition: eq(variables['node_version'], '8.x')
