jobs:
- template: azure-pipelines-npm-template.yml
  parameters:
    name: Linux
    vmImage: ubuntu-16.04

- template: azure-pipelines-npm-template.yml
  parameters:
    name: Windows
    vmImage: vs2017-win2016

- template: azure-pipelines-npm-template.yml
  parameters:
    name: Mac
    vmImage: macOS-10.13
